[project]
name = "demanda-servicios-salud-cdmx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lucas-G-A", email = "lucas.g.a@icloud.com" }
]
requires-python = ">=3.11"
dependencies = [
    "anthropic>=1.4.0",
    "geopandas>=1.1.4",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "plotly>=7.0.0",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.0",
    "scipy>=1.17.1",
    "streamlit>=1.63.0",
    "xlrd>=2.0.2",
]

[project.scripts]
demanda-servicios-salud-cdmx = "demanda_servicios_salud_cdmx:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
